In [1]:
import random

In [2]:
random.randint(0, 100)

62

In [3]:
import pandas as pd

In [4]:
from pandas import Series, DataFrame

# Data types: Series and DataFrame

In [5]:
s = Series(    [10, 20, 30, 40, 50, 60, 70]     )

In [6]:
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [7]:
s[0]

10

In [8]:
s[1]

20

In [9]:
s = Series(    'this is a test'.split()  )
s

0    this
1      is
2       a
3    test
dtype: object

In [10]:
s = Series(    [10, 20, 30, 40, 50, 60, 70]     )
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [11]:
# slice?
s[2:5]

2    30
3    40
4    50
dtype: int64

In [12]:
s[3] = 999
s

0     10
1     20
2     30
3    999
4     50
5     60
6     70
dtype: int64

In [13]:
s[4] = 12.34

/tmp/ipykernel_1583/2558586753.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '12.34' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  s[4] = 12.34


In [14]:
s

0     10.00
1     20.00
2     30.00
3    999.00
4     12.34
5     60.00
6     70.00
dtype: float64

In [15]:
s[5] = 'hello'

/tmp/ipykernel_1583/1284062357.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'hello' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  s[5] = 'hello'


In [16]:
s

0     10.0
1     20.0
2     30.0
3    999.0
4    12.34
5    hello
6     70.0
dtype: object

In [17]:
s = Series(    [10, 20, 30, 40, 50, 60, 70]     )
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [18]:
# methods

s.sum()

280

In [19]:
s.min()

10

In [20]:
s.max()

70

In [21]:
s.mean()

40.0

In [22]:
s.std()

21.602468994692867

In [23]:
s.median()

40.0

In [24]:
s.quantile(0.25)

25.0

In [25]:
s.quantile(0.75)

55.0

In [26]:
s.describe()

count     7.000000
mean     40.000000
std      21.602469
min      10.000000
25%      25.000000
50%      40.000000
75%      55.000000
max      70.000000
dtype: float64

# Exercise: Temperature

1. Define a series with 10 integers, the max temp forecast for the next 10 days.
2. Get the descriptive statistics with `describe`.
3. In the first 5 days, what will be the max temp?

In [27]:
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64

In [28]:
# first 3 values

s[:3]

0    10
1    20
2    30
dtype: int64

In [29]:
s[0:3]

0    10
1    20
2    30
dtype: int64

In [30]:
s[0:4]

0    10
1    20
2    30
3    40
dtype: int64

In [31]:
s = Series([18, 18, 19, 20, 19, 20, 19, 20, 21, 19])
s

0    18
1    18
2    19
3    20
4    19
5    20
6    19
7    20
8    21
9    19
dtype: int64

In [32]:
s.describe()

count    10.000000
mean     19.300000
std       0.948683
min      18.000000
25%      19.000000
50%      19.000000
75%      20.000000
max      21.000000
dtype: float64

In [33]:
s[:5]

0    18
1    18
2    19
3    20
4    19
dtype: int64

In [34]:
s[:5].max()

20

In [35]:
s

0    18
1    18
2    19
3    20
4    19
5    20
6    19
7    20
8    21
9    19
dtype: int64

# Index

In Pandas, we can decide what the index will be!

We can use any values we want there.

In [38]:
s = Series([10, 20, 30, 40, 50],
          index=[5, 10, 15, 20, 300])
s

5      10
10     20
15     30
20     40
300    50
dtype: int64

In [39]:
s[4]

KeyError: 4

# Two ways to retrieve

1. `.loc` -- retrieve via the index, using `[]`
2. `.iloc` -- retrieve via the position, using `[]`, starting at position 0

In [40]:
s

5      10
10     20
15     30
20     40
300    50
dtype: int64

In [41]:
s.loc[10]

20

In [42]:
s.loc[20]

40

In [44]:
s.loc[10:20]   # .loc returns a slice UP TO AND INCLUDING

10    20
15    30
20    40
dtype: int64

In [45]:
s.iloc[2:4]

15    30
20    40
dtype: int64

In [46]:
s = Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [47]:
s + s

0     20
1     40
2     60
3     80
4    100
dtype: int64

In [48]:
t = Series([100, 200, 300])

s + t

0    110.0
1    220.0
2    330.0
3      NaN
4      NaN
dtype: float64

In [49]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [50]:
# broadcast

s + 3

0    13
1    23
2    33
3    43
4    53
dtype: int64

In [51]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [52]:
s.loc[0]

10

In [53]:
s.loc[1]

20

In [54]:
# fancy indexing -- give a list of indexes to []
s.loc[ [0, 1]  ]

0    10
1    20
dtype: int64

In [55]:
s.loc[ [0, 2, 0] ]

0    10
2    30
0    10
dtype: int64

In [56]:
s = Series([10, 20, 30, 40, 50],
          index=list('abcde'))
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [57]:
s.loc['a']

10

In [58]:
s.loc['b']

20

In [59]:
s.loc[['a', 'c']]

a    10
c    30
dtype: int64

In [60]:
s.loc['b':'d']

b    20
c    30
d    40
dtype: int64

In [61]:
s = Series([10, 20, 30, 40, 50],
          index=list('abc'))
s

ValueError: Length of values (5) does not match length of index (3)

In [62]:
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [63]:
t = Series([100, 200, 300, 400, 500],
          index=list('edcba'))
t

e    100
d    200
c    300
b    400
a    500
dtype: int64

In [64]:
s + t

a    510
b    420
c    330
d    240
e    150
dtype: int64

In [65]:
s * t

a    5000
b    8000
c    9000
d    8000
e    5000
dtype: int64

In [66]:
t.T

e    100
d    200
c    300
b    400
a    500
dtype: int64

In [67]:
s.values

array([10, 20, 30, 40, 50])

In [68]:
s.values * t.values.T

array([ 1000,  4000,  9000, 16000, 25000])

In [69]:
t.values.T

array([100, 200, 300, 400, 500])

In [70]:
t.values

array([100, 200, 300, 400, 500])

In [72]:
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [74]:
# matrix multiplication

s.dot(s)

5500

In [75]:
s = Series([10, 20, 30, 40, 50],
          index=list('abcab'))
s

a    10
b    20
c    30
a    40
b    50
dtype: int64

In [76]:
s.loc['c']

30

In [77]:
s.loc['a']

a    10
a    40
dtype: int64

In [78]:
s.loc['b']

b    20
b    50
dtype: int64

In [79]:
s.loc[ ['a', 'b'] ]

a    10
a    40
b    20
b    50
dtype: int64

In [80]:
t

e    100
d    200
c    300
b    400
a    500
dtype: int64

In [81]:
s + t

a    510.0
a    540.0
b    420.0
b    450.0
c    330.0
d      NaN
e      NaN
dtype: float64

In [82]:
t = Series([100, 200, 300, 400, 500],
          index=list('bcdba'))

In [83]:
s + t

a    510.0
a    540.0
b    120.0
b    420.0
b    150.0
b    450.0
c    230.0
d      NaN
dtype: float64

In [84]:
s.index

Index(['a', 'b', 'c', 'a', 'b'], dtype='object')

In [85]:
a = Series([10, 20, 30])
a

0    10
1    20
2    30
dtype: int64

In [86]:
a.index

RangeIndex(start=0, stop=3, step=1)

In [87]:
s

a    10
b    20
c    30
a    40
b    50
dtype: int64

In [91]:
x

NameError: name 'z' is not defined

In [92]:
len(dir(s))

422

In [93]:
len(dir(pd))

140

# Exercise: Temperatures

1. Define a series, `highs`, with the 10-day high-temperature forecast for the next 10 days. The index should be a string with two digits for the date.
2. Define a series, `lows`, with the same thing, but with the expected low temperatures.
3. Define a series, `diffs`, that is the difference between the highs and lows.
4. Retrieve the diffs for 05.12 - 10.12.
5. Run `describe` on the first 5 days in `diffs`.

In [96]:
highs = Series([18, 18, 19, 20, 19, 20, 19, 20, 21, 19],
              index='02 03 04 05 06 07 08 09 10 11'.split())
lows = Series([6, 8, 8, 9, 8, 9, 8, 9, 8, 7],
              index='02 03 04 05 06 07 08 09 10 11'.split())


In [97]:
highs

02    18
03    18
04    19
05    20
06    19
07    20
08    19
09    20
10    21
11    19
dtype: int64

In [98]:
highs - lows

02    12
03    10
04    11
05    11
06    11
07    11
08    11
09    11
10    13
11    12
dtype: int64

In [99]:
diffs = highs - lows

In [103]:
diffs.loc['05':'09']

05    11
06    11
07    11
08    11
09    11
dtype: int64

In [104]:
diffs.loc['05':'09'].describe()

count     5.0
mean     11.0
std       0.0
min      11.0
25%      11.0
50%      11.0
75%      11.0
max      11.0
dtype: float64

# What we *don't* use in Pandas

- `if`
- `for`

How, then, can we retrieve values that we want?

In [105]:
s * 3

a     30
b     60
c     90
a    120
b    150
dtype: int64

In [106]:
s

a    10
b    20
c    30
a    40
b    50
dtype: int64

In [107]:
s = Series( [10, 20, 30, 40, 50],
          index=list('abcde'))
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [108]:
# broadcast

s + 30

a    40
b    50
c    60
d    70
e    80
dtype: int64

In [109]:
s / 10

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

In [110]:
# what if I use == ?

s == 30

a    False
b    False
c     True
d    False
e    False
dtype: bool

In [111]:
# I get back a series of booleans!

In [112]:
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [113]:
s.loc['b']

20

In [114]:
s.loc[['a', 'b', 'c', 'e']]

a    10
b    20
c    30
e    50
dtype: int64

In [116]:
# what if we use booleans (True/False) in a list?
# we only get the values back for which we have True

# boolean index , mask index

s.loc[ [True, False, True, False, True] ]

a    10
c    30
e    50
dtype: int64

In [117]:
s.loc[ [1, 0, 1, 0, 1] ]

KeyError: "None of [Index([1, 0, 1, 0, 1], dtype='int64')] are in the [index]"

In [118]:
s = Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [119]:
s.loc[[0,1,1,0,1]]   # fancy index, because they're integers

0    10
1    20
1    20
0    10
1    20
dtype: int64

In [120]:
s.loc[[False, True, True, False, True]]

1    20
2    30
4    50
dtype: int64

In [123]:
# What's happening here?
# 1. s == 30 returns a series of booleans (True/False)
# 2. We put the boolean series in []
# 3. We give it to .loc
# 4. We get back values of s where the boolean was True

s.loc[ s == 30 ]

2    30
dtype: int64

In [124]:
s.loc[ s < s.mean() ]

0    10
1    20
dtype: int64

In [125]:
s.loc[ s < s.mean() - s.std() ]

0    10
dtype: int64

In [126]:
s + 3

0    13
1    23
2    33
3    43
4    53
dtype: int64

In [127]:
s < 50

0     True
1     True
2     True
3     True
4    False
dtype: bool

# Exercise: Family

1. Create a series in which the index contains people's names, and the values are their ages. Have at least 5 elements.
2. Find all of the family members whose ages are above the mean.
3. Are there any people whose ages are 1 standard deviation below the mean?

In [128]:
s = Series([54, 52, 23, 21, 19],
          index='Reuven Shira Atara Shikma Amotz'.split())  # keyword argument
s

Reuven    54
Shira     52
Atara     23
Shikma    21
Amotz     19
dtype: int64

In [129]:
s.mean()

33.8

In [130]:
s.max()

54

In [131]:
s.min()

19

In [133]:
s.loc[   s > s.mean()  ]

Reuven    54
Shira     52
dtype: int64

In [135]:
s.loc[ s <  s.mean() - s.std()  ]

Series([], dtype: int64)

In [136]:
s.loc[ s <  s.mean() - s.std()  ].count()

0

In [141]:
s = Series([10, 20, 30, 20, 30, 20, 30, 30, 90, 100],
          index=list('abcdefghij'))
s

a     10
b     20
c     30
d     20
e     30
f     20
g     30
h     30
i     90
j    100
dtype: int64

In [142]:
# what if I want the first five?
s.iloc[:5]

a    10
b    20
c    30
d    20
e    30
dtype: int64

In [143]:
s.head(5)

a    10
b    20
c    30
d    20
e    30
dtype: int64

In [144]:
s.tail(5)

f     20
g     30
h     30
i     90
j    100
dtype: int64

In [145]:
# how many times does each value appear?
s.value_counts()

30     4
20     3
10     1
90     1
100    1
Name: count, dtype: int64

In [146]:
# what if I want to know the 2 items that are most common?

s.value_counts().head(2)

30    4
20    3
Name: count, dtype: int64

In [147]:
# I want to know the percentage of each value in s

s.value_counts() / s.count()

30     0.4
20     0.3
10     0.1
90     0.1
100    0.1
Name: count, dtype: float64

In [148]:
s.value_counts(normalize=True)

30     0.4
20     0.3
10     0.1
90     0.1
100    0.1
Name: proportion, dtype: float64

In [149]:
help(s.value_counts)

Help on method value_counts in module pandas.core.base:

value_counts(normalize: 'bool' = False, sort: 'bool' = True, ascending: 'bool' = False, bins=None, dropna: 'bool' = True) -> 'Series' method of pandas.core.series.Series instance
    Return a Series containing counts of unique values.

    The resulting object will be in descending order so that the
    first element is the most frequently-occurring element.
    Excludes NA values by default.

    Parameters
    ----------
    normalize : bool, default False
        If True then the object returned will contain the relative
        frequencies of the unique values.
    sort : bool, default True
        Sort by frequencies when True. Preserve the order of the data when False.
    ascending : bool, default False
        Sort in ascending order.
    bins : int, optional
        Rather than count values, group them into half-open bins,
        a convenience for ``pd.cut``, only works with numeric data.
    dropna : bool, default True

# `dtype`

`dtype` is a NumPy/Pandas idea -- a C data type.  Every series has a dtype. All of the values in that series have the same dtype.

In [150]:
s = Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [151]:
2 ** 64   # 2 to the 64th power

18446744073709551616

In [152]:
s = Series([10, 20, 30, 40, 50], dtype='int32')
s

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [153]:
s = Series([10, 20, 30, 40, 50], dtype='int8')
s

0    10
1    20
2    30
3    40
4    50
dtype: int8

In [154]:
s * 10

0    100
1    -56
2     44
3   -112
4    -12
dtype: int8

In [155]:
2 ** 8

256

In [156]:
2 ** 32

4294967296

In [157]:
2 ** 54

18014398509481984

In [158]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int8

# dtype

- `int`
    - `int8`
    - `int16`
    - `int32`
    - `int64` (default)
- `float`
    - `float16`
    - `float32`
    - `float64` (default)
- `uint` (unsigned int)
    - `uint8`
    - `uint16`
    - `uint32`
    - `uint64`
- `object` (string, more or less)

In [164]:
s = Series('hello out there'.split(), dtype='uint64')

ValueError: invalid literal for int() with base 10: 'hello'

In [165]:
s = Series([10, 20, 30, 40, 50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [166]:
s.loc[2]= 12.34
s

/tmp/ipykernel_1583/3505832813.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '12.34' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  s.loc[2]= 12.34


0    10.00
1    20.00
2    12.34
3    40.00
4    50.00
dtype: float64

In [172]:
# the right way to do this... 
# use .astype

s = Series([10, 20, 30, 40, 50])
s = s.astype('float64')
s.loc[2] = 12.345
s

0    10.000
1    20.000
2    12.345
3    40.000
4    50.000
dtype: float64

In [169]:
s = Series([1.23, 4.56, 7.89])
s

0    1.23
1    4.56
2    7.89
dtype: float64

In [170]:
s.astype('int64')

0    1
1    4
2    7
dtype: int64

In [171]:
s.round()

0    1.0
1    5.0
2    8.0
dtype: float64

# Exercise: Temps

1. Define `highs` again, with the high temps predicted for the next 10 days.
2. Convert all of the temperatures to Fahrenheit. This will result in floats.
3. Convert to ints, ignoring/removing the fractional part.
4. What dtype of int should we use here, to avoid losing data?

In [174]:
highs = Series([18, 18, 19, 20, 19, 20, 19, 20, 21, 19],
              index='02 03 04 05 06 07 08 09 10 11'.split(), dtype='int8')
highs

02    18
03    18
04    19
05    20
06    19
07    20
08    19
09    20
10    21
11    19
dtype: int8

In [181]:
(highs * 9/5) + 32

02    13.2
03    13.2
04    15.0
05    16.8
06    15.0
07    16.8
08    15.0
09    16.8
10    18.6
11    15.0
dtype: float64

In [182]:
((highs * 9/5) + 32).astype('int8')

02    13
03    13
04    15
05    16
06    15
07    16
08    15
09    16
10    18
11    15
dtype: int8

# `NaN` -- "not a number"

`NaN` means that we don't have a value. 

In [184]:
test_scores = Series([88, 95, 97, 85, 90])
test_scores.mean()

91.0

In [185]:
test_scores = Series([88, 95, 97, 85, 0])
test_scores.mean()

73.0

In [186]:
import numpy as np

test_scores = Series([88, 95, 97, 85, np.nan])
test_scores.mean()

91.25

In [187]:
type(np.nan)

float

In [188]:
np.nan == np.nan

False

In [189]:
s = Series([10, 20, 30, np.nan, 50])
s

0    10.0
1    20.0
2    30.0
3     NaN
4    50.0
dtype: float64

In [190]:
s.sum()

110.0

In [192]:
s = Series([10, 20, 30, pd.NA, 50])
s

0      10
1      20
2      30
3    <NA>
4      50
dtype: object